[package]
authors = ["Paul Collier <paul@paulcollier.ca>"]
name = "cantide"
version = "0.1.0"

[dependencies]
chrono = "0.3"
error-chain = "0.10.0"
irc = "0.12"
rand = "0.3"

[dependencies.postgres]
features = ["with-chrono"]
version = "0.14"
